server:
  port: 80


spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  username: root
  password: 1qazXSW@3edc
 thymeleaf:
  cache: false
  content-type: text/html
  mode: LEGACYHTML5
  
  freemarker:
   template-loader-path: classpath:/templates/
   cache: false
   charset: UTF-8
  http:
   multipart:
    enable: true
    file-size-threshold: 0
    max-file-size: 100Mb
    max-request-size: 100Mb
    maxFileSize: 100Mb
    
 
 #如果没有这个配置项，则必须在resources/processes里面有bpmn
 activiti:
  check-process-definitions: false
  #全量历史记录
  history-level: full
  async-executor-activate: false
  
eis:
  super-user-id: 1
  posyspath: /home/eis/pageoffice/lic
  #
  popassword: 111111
  basepath: /home/eis/eis/base
  
 
 
 

 #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ai.entity
  mapperLocations: classpath:mapping/*.xml
  
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl 

logging:
   level:
      com.ai.eis.mapper : debug
   config: classpath:log4j2.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql